controller:
   resource: ../src/Controller/
   type: attribute

contact:
   path: /contact
   controller: App\Controller\Controller::contact


patient_index:
   path: /patient/
   controller: App\Controller\Controller::patientsIndex

patient_new:
   path: /patient/new
   controller: App\Controller\Controller::patientsNew

patient_edit:
   path: /patient/{id}/edit
   controller: App\Controller\Controller::patientsEdit

patient_delete:
   path: /patient/{id}
   controller: App\Controller\Controller::patientsDelete
   methods: POST

number:
  path: /number
  controller: App\Controller\Controller::number

index:
  path: /
  controller: App\Controller\Controller::index

